http:
  port: 3000
admin:
  port: 9876
  host: localhost
apiEndpoints:
  callcentreagents:
    paths: '/CallCentreAgents'
  client:
    paths: '/Client'
  complaintrequest:
    paths: '/ComplaintRequests'
  insertcallog:
    paths: '/InsertCallLog'
  checkcredentials:
    paths: '/CheckCredentials'
serviceEndpoints:
  httpbin:
    url: 'http://localhost:3030'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - callcentreagents
      - client
      - complaintrequest
      - insertcallog
      - checkcredentials
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
